dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
script:
- python -m unittest discover
deploy:
  provider: pypi
  username: ericlingit
  password:
    secure: m4FvCEXPTipkC/aZUvfL+Q5Vi34YOidmFKJUTPoL34RHTRs3Ee/2E1+N4rcEsa7Yg6dJyPDsmfwZJyoq170P1WIX6VWxnhEvbj1IrwvqNNoswvza05KcukP7UzwMqYjFWRGqwh8XXpBFHB016i+qEG/IhGBWdVvLLQj7cV9bo6xcklGQEBtMJofKSfovrzDT7EUDEuvyjnHPrVNStL+NG1co2BEjPEr0ut/QO68tk++5MM+WbX3iEhlZMrmihLb1o4RYCVlg8nOMXZW/6uiqJHY82aHBIv+dnOdIEVD5WUe5XnpleO3JVGvpUPBnCUgGKBCJ+19JuIZkZF4vaaA6kzyBnopyqfl9R/2N+dVrxleoEux/R+lR/kRR8APUhD+SsYOJPvrwBMpnxYrFkVKihoM/yFwaZqygfzbBQsnzyKwj2pX6elRyABjN5wMLMVcG65WlQkn8fzsqd7ZoJlxFjXw4fOA3Rar1aK78OlVosfeBhOKZXw6bxU7/AP6fKaJ7UmPy+dD3s64yh1dYqlzCS1xHAqo7rKiRzqQVkFlI6Y/yprrPPqmh0Q9BIrgo6fKOXRUK9KZnZWWy/QTPJroOV4MAwQskpxTSa2Irubnf6iklIGULdEarE+gjkHEIZKF+JTFLs8NfvOwbwOhmwCSjXOIi0ynUKt8aTeTChPMsldY=
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
