dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
script:
- python -m unittest discover
deploy:
  provider: pypi
  username: __token__
  password:
    secure: F/rjVipG8nAegM53zagp34vDnLPRN7Gjx5Sfwgkqz9tXUwxYsuCdKBgx3tnE4ob3j4j0G+hv6yUv1LTUmFwGOZa8UViMhGNZv1W5Y7wyGSBbYmfemdeIgyi3zoGEnEdGY/liF+Q55lcQ+jsgJppK/cCKZ/0SaowLkDUEDPNDPqHEF3s++NdUf22xEATHyI5M0wDFfaXA/vChytiK5hbri10fP9gDo1V7gJV9IXzgX2BgZbB8yRfXYujcLUphstDRJ/fZMyc5rcKPioNHhQf6ltK2fzQcKSkSJXzDE1NMSEGZEBLt/249IKJUb7W8ysZaPx74slEaZXniRZtim5dd32lPtCPpBlbxH/n6pubXgDdMTyyvfyCP628bk0QZiSn045CholjZGRcZyUxzNEGzpfZZMTHNaKGSO56aBCawDLd0+nzL4NuwBIQfMmaMLFaOt4gaQKZ5qjq8SkCPSkvSakxjbK6JMIOJTmEJ2pTHi6FFhsLeXg4JJ39749qXUwNwTcZWqcmHQXPQBqFjfg1uUcbpFjXsz47EB0AJfVigKwkfTMpRYD/HJAeEuL/x15i0yFtQfWJ377v6SY9RSz3a6MaIJ7pW9njyJco2IrCffO4Mu+fSXycWREE8VcXru7qPz33DeWRkZYp+/6moA/4IfnS2wI9LXNPKkKKAE63R9xo=
  server: "https://test.pypi.org/legacy/"
  distributions: "sdist bdist_wheel"
